### ISSUE TITLE
Formatting for European dates

### ISSUE THREAD

**Issue by AllThingsSmitty** [frontendfront/front-end-conferences#14]
For readability purposes should the formatting of European dates for the standard DDMMYYY? Right now MMDDYYYY is used for both Europe and North America.

**Comment by frontendfront** [comment]
You raise a good point. I guess I missed this issue because when I write in English I tend to use the American format for dates. So, yeah, as long as the month stays text, I think it's a good idea to move the day in front for European conferences.

**Comment by AllThingsSmitty** [comment]
I think that will work, sort of globalizing the static information more. If I have time I might do a PR tomorrow.
