### ISSUE TITLE
Add Frontend United

### ISSUE THREAD

**Issue by BarisW** [frontendfront/front-end-conferences#236]
Not sure if this is the way to go: https://github.com/BarisW/front-end-conferences/pull/1

If not, here is the code

```
[**Frontend United**](https://frontendunited.org/)  
31 May - 3 June 2018  
Utrecht, **The Netherlands** 
```

**Comment by frontendfront** [comment]
It's added. Cheers!

**Comment by BarisW** [comment]
Thanks! I don't see it yet though? https://frontendfront.com/conferences/
Is it already deployed?

**Comment by frontendfront** [comment]
It's also on the website now.
