### ISSUE TITLE
Add FrontConf in April

### ISSUE THREAD

**Issue by like-me1** [frontendfront/front-end-conferences#328]
Trying to create a PR with adding a FrontConf (Munich Frontend Conference) in April. But failed with authorization. 

[**Munich Frontend Conference FrontConf**](https://frontconf.com/)  
27 April 2019  
Munich, **Germany**

**Comment by frontendfront** [comment]
I added FrontConf myself, so that part is solved. But I have no idea why it failed with authorization.

**Comment by like-me1** [comment]
Thanks a lot!Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail13.12.2018, 14:48, "Front-end Front" <notifications@github.com>:I added FrontConf myself, so that part is solved. But I have no idea why it failed with authorization.
