### ISSUE TITLE
How about to add a hashtag on each item ? 

### ISSUE THREAD

**Issue by sotayamashita** [frontendfront/front-end-conferences#77]

**Comment by frontendfront** [comment]
You mean a hashtag for Twitter?

**Comment by sotayamashita** [comment]
@frontendfront yes

**Comment by frontendfront** [comment]
I wouldn't mind if there was a hashtag next to the name of the conference.

**Comment by sotayamashita** [comment]
@frontendfront Thank you. I will add hash tag.
